# permissions for end users to edit podchaos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chaos-guru
    app.kubernetes.io/managed-by: kustomize
  name: podchaos-editor-role
rules:
- apiGroups:
  - chaos.chaos.guru
  resources:
  - podchaos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.chaos.guru
  resources:
  - podchaos/status
  verbs:
  - get
