# permissions for end users to view podchaos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chaos-guru
    app.kubernetes.io/managed-by: kustomize
  name: podchaos-viewer-role
rules:
- apiGroups:
  - chaos.chaos.guru
  resources:
  - podchaos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chaos.chaos.guru
  resources:
  - podchaos/status
  verbs:
  - get
